version: '3.8'

services:
  stage-webapi:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_VERSION=7.0.14
      - ASPNET_VERSION=7.0.14
    ports:
      - "4433:443"
      - "8080:80"
    network_mode: "host"
    # networks:
    #   - stage_net
    
#   sql_server:
#     image: mcr.microsoft.com/mssql/server
#     environment:
#       SA_PASSWORD: "123Mudar"
#       ACCEPT_EULA: "Y"
#       MSSQL_PID: Developer
#     ports:
#       - "1433:1433"
#     networks:
#       - stage_net

# networks:
#   stage_net: